//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajaGreyMatter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class greymatterpiEntities : DbContext
    {
        public greymatterpiEntities()
            : base("name=greymatterpiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<jedinicnamjera> jedinicnamjera { get; set; }
        public DbSet<klijent> klijent { get; set; }
        public DbSet<lijek> lijek { get; set; }
        public DbSet<narudzbenica> narudzbenica { get; set; }
        public DbSet<stavkenarudzbenice> stavkenarudzbenice { get; set; }
        public DbSet<tiplijeka> tiplijeka { get; set; }
        public DbSet<zaposlenik> zaposlenik { get; set; }
    }
}
