//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajaGreyMatter
{
    using System;
    using System.Collections.Generic;
    
    public partial class jedinicnamjera
    {
        public jedinicnamjera()
        {
            this.lijek = new HashSet<lijek>();
        }
    
        public int idJedinicnaMjera { get; set; }
        public string naziv { get; set; }
        public string kratica { get; set; }
    
        public virtual ICollection<lijek> lijek { get; set; }
    }
}
