//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajaGreyMatter
{
    using System;
    using System.Collections.Generic;
    
    public partial class lijek
    {
        public lijek()
        {
            this.stavkenarudzbenice = new HashSet<stavkenarudzbenice>();
        }
    
        public int idLijek { get; set; }
        public string naziv { get; set; }
        public string upute { get; set; }
        public System.DateTime datumProizvodnje { get; set; }
        public System.DateTime rokUpotrebe { get; set; }
        public float cijena { get; set; }
        public float pakiranje { get; set; }
        public float doza { get; set; }
        public int idJedinicnaMjera { get; set; }
        public int idTipLijeka { get; set; }
        public int kolicina { get; set; }
    
        public virtual jedinicnamjera jedinicnamjera { get; set; }
        public virtual tiplijeka tiplijeka { get; set; }
        public virtual ICollection<stavkenarudzbenice> stavkenarudzbenice { get; set; }
    }
}
