//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajaGreyMatter
{
    using System;
    using System.Collections.Generic;
    
    public partial class narudzbenica
    {
        public narudzbenica()
        {
            this.stavkenarudzbenice = new HashSet<stavkenarudzbenice>();
        }
    
        public int idNarudzbenice { get; set; }
        public string oibKlijenta { get; set; }
        public System.DateTime datumIzdavanja { get; set; }
        public string oibZaposlenika { get; set; }
        public System.DateTime rokPlacanja { get; set; }
        public int status { get; set; }
    
        public virtual klijent klijent { get; set; }
        public virtual zaposlenik zaposlenik { get; set; }
        public virtual ICollection<stavkenarudzbenice> stavkenarudzbenice { get; set; }
    }
}
