//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajaGreyMatter
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavkenarudzbenice
    {
        public int idLijek { get; set; }
        public int idNarudzbenice { get; set; }
        public int kolicina { get; set; }
    
        public virtual lijek lijek { get; set; }
        public virtual narudzbenica narudzbenica { get; set; }
    }
}
