//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdajaGreyMatter
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenik
    {
        public zaposlenik()
        {
            this.narudzbenica = new HashSet<narudzbenica>();
        }
    
        public string oib { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string adresa { get; set; }
        public string brojTelefona { get; set; }
        public string korisnickoIme { get; set; }
        public string lozinka { get; set; }
    
        public virtual ICollection<narudzbenica> narudzbenica { get; set; }
    }
}
